min_version = "2025.12.12"

[tasks."mysql:configure"]
sources = [
    "mysql-server/**/CMakeLists.txt",
    "mysql-server/cmake/**",
    "!mysql-server/build/**",
    "!mysql-server/run/**",
    "!mysql-server/mysql-test/**",
]
run = """
ln -sfn ../../src mysql-server/storage/toydb

cd mysql-server
mkdir -p build
cd build

cmake .. -DWITH_DEBUG=1 -DDOWNLOAD_BOOST=1 -DWITH_BOOST=../boost -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
"""

[tasks."mysql:gen-header"]
depends = ["mysql:configure"]
run = """
cd mysql-server/build
cmake --build . --target GenError
"""

[tasks."mysql:build"]
depends = ["mysql:configure"]
sources = [
    "mysql-server/**/*",
    "src/**/*",
    "!mysql-server/build/**",
    "!mysql-server/run/**",
    "!mysql-server/mysql-test/**",
]
dir = "mysql-server"
run = """
ln -sfn ../../src storage/toydb

cd build
# TODO: pass number of cpu cores dynamically
make -j16 --
"""

[tasks."mysql:build-storage-engine"]
depends = ["mysql:configure"]
sources = ["src/**/*"]
dir = "mysql-server"
run = """
ln -sfn ../../src storage/toydb

cd build
cmake --build . --target toydb -- -j12
"""

[tasks."mysql:run-init"]
depends = ["mysql:build"]
dir = "mysql-server"
# https://dev.mysql.com/doc/refman/8.4/en/data-directory-initialization.html
run = """
rm -rf run/data
mkdir -p run/data

cat <<EOF > run/my.cnf
[mysqld]
basedir=${PWD}/build
datadir=${PWD}/run/data
disable_log_bin
EOF

# Set root password and install toydb
cat <<EOF > run/init.sql
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
INSTALL PLUGIN toydb SONAME "ha_toydb.so";
EOF

build/bin/mysqld --defaults-file=run/my.cnf --initialize-insecure --init-file=${PWD}/run/init.sql
"""

[tasks."mysql:run"]
depends = ["mysql:build"]
dir = "mysql-server"
# https://dev.mysql.com/doc/refman/8.4/en/starting-server.html
# https://dev.mysql.com/doc/refman/8.4/en/dbug-package.html
run = """
build/bin/mysqld --defaults-file=run/my.cnf --debug='d,toydb:i:T'
"""

[tasks."mysql:stop"]
dir = "mysql-server"
run = """
build/bin/mysqladmin -u root -proot shutdown
"""

[tasks."mysql:e2e"]
depends = ["mysql:build"]
dir = "mysql-server"
run = """
ln -sfn ../../../mysql-test/toydb mysql-test/suite/toydb
build/mysql-test/mysql-test-run.pl --suite=toydb --mysqld="--skip-log-bin"
"""

[tasks."mysql:gen-e2e-results"]
depends = ["mysql:build"]
dir = "mysql-server"
# https://dev.mysql.com/doc/dev/mysql-server/8.0.44/PAGE_GENERATE_TESTCASE_RESULT_FILE.html
run = """
ln -sfn ../../../mysql-test/toydb mysql-test/suite/toydb
build/mysql-test/mysql-test-run.pl --suite=toydb --record --mysqld="--skip-log-bin"
"""

[tasks.fmt]
run = """
find src .vscode -name "*.cc" -o -name "*.h" \
| xargs clang-format -i
"""

[tasks."fmt:check"]
run = """
find src .vscode -name "*.cc" -o -name "*.h" \
| xargs clang-format --dry-run --Werror
"""

[tasks.lint]
run = """
find src -name "*.cc" -o -name "*.h" \
| xargs clang-tidy -p mysql-server/build --extra-arg=-isystem --extra-arg="$LIBCXX_INCLUDE_PATH"
"""

[tasks."lint:fix"]
run = """
find src -name "*.cc" -o -name "*.h" \
| xargs clang-tidy -fix -p mysql-server/build --extra-arg=-isystem --extra-arg="$LIBCXX_INCLUDE_PATH"
"""
